### ISSUE TITLE
I installed the mod for key 6, but minecraft crashes

### ISSUE THREAD

**Issue by DaffierYou5000** [simply-kel/SimplyStatus-fabric#18]
what to do?

**Comment by kel-cu** [comment]
Can I have the logs, please? I don't understand a damn thing.

**Comment by DaffierYou5000** [comment]
I can’t upload the logs, they are too big

**Comment by ImGRUI** [comment]
Upload logs to https://mclo.gs/

**Comment by kel-cu** [comment]
Issue closed due to author inactivity
