### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 78845544** [simply-kel/SimplyStatus-fabric#19]
![image](https://github.com/kel-cu/SimplyStatus/assets/128615203/f3f018fc-329e-4d33-b3d8-13297b751b9a)

**Comment by 78845544** [comment]
help pls

**Comment by kel-cu** [comment]
I can't tell anything from this screenshot, please send your logs via https://mclo.gs/

<hr>

По данному скриншоту я не могу ничего сказать, пожалуйста, пришлите свои логи через https://mclo.gs/

**Comment by 78845544** [comment]
https://mclo.gs/LP2mGjc

**Comment by kel-cu** [comment]
Awww, well this is the version for 1.20.1, which is no longer supported. Also most likely the errors are related to avatars in status
The most I can recommend is to use newer versions of the game and mod. If you need a server, you can use ViaFabric

<hr>

Оууу, ну тут версия для 1.20.1, которое уже не поддерживается. Также скорее всего ошибки связаны с аватарками в статусе
Максимум, что я могу посоветовать, это использовать более новые версии игры и мода. Если вам нужен сервер, вы можете использовать ViaFabric
