### ISSUE TITLE
Not Working when in a Flashback replay

### ISSUE THREAD

**Issue by ThatCuteOne** [simply-kel/SimplyStatus-fabric#23]
1. It does not work(picture 1)
2. It spams the console with "[Render thread/ERROR]: [SimplyStatus] null"(picture 2)

![grafik](https://github.com/user-attachments/assets/5c64b826-488d-47d7-911b-44e5520f08fa)

![grafik](https://github.com/user-attachments/assets/7bd4e10a-2a26-4331-b3ef-bb3a8aa9c443)

**Comment by ImGRUI** [comment]
Flashback support has not been added yet, and dev recently made project ARR, which makes support unknown in the future.

**Comment by ImGRUI** [comment]
I looked up Flashback discord, dev said that they'll probably keep updating the source code.

**Comment by kel-cu** [comment]
Fixed - [2.2.0-alpha.8](https://modrinth.com/mod/simplystatus/version/2.2.0-alpha.8)
