### ISSUE TITLE
How do I disable the held item tooltip in the RPC?

### ISSUE THREAD

**Issue by RaptaG** [simply-kel/SimplyStatus-fabric#3]
The only option is for the offhand item.

OS: Linux
Launcher: Prism Launcher

(From: https://git.simplykel.ru/kel/SimplyStatus/issues/1)

**Comment by simply-kel** [comment]
Do you mean completely disabling the display of items in the hands?
If so, perhaps I will implement this in the next update.

**Comment by RaptaG** [comment]
> Do you mean completely disabling the display of items in the hands? If so, perhaps I will implement this in the next update.

Yes that's what I meant.

Also could you add so that in the RPC only an image is displayed, not the day time.

**Comment by simply-kel** [comment]
Changes have been made to the [commit](https://github.com/simply-kel/SimplyStatus-fabric/commit/a85fa3a62029fafb0883873fbdb73108b074ff06)

**Comment by RaptaG** [comment]
Thanks!!

**Comment by RaptaG** [comment]
Btw could you please add an English description too on your commits?

**Comment by simply-kel** [comment]
Oh, I wanted to, but I forgot.
