### ISSUE TITLE
Allow for custom titles

### ISSUE THREAD

**Issue by RaptaG** [simply-kel/SimplyStatus-fabric#4]
Right now the only RPC titles are `SimpleStatus` and `Minecraft`. Could you make it so that users cab also add custom titles of their own?

**Comment by simply-kel** [comment]
I can't speculate at this point, maybe there will be a possibility, but it would require registering the user app in Discord as it is done now: by changing the app ID + upload images for work. Yes, perhaps I will make it so that thumbnail links are used

**Comment by RaptaG** [comment]
🎉
