### ISSUE TITLE
Заменить эмодзи статистики

### ISSUE THREAD

**Issue by Sidiusz** [simply-kel/SimplyStatus-fabric#6]
Предлагаю заменить стандартные эмодзи в статистике на ❤: %health% | ⛊: %armor%
![image](https://github.com/simply-kel/SimplyStatus-fabric/assets/20544939/a748b4ba-41a5-4b16-a574-8111d6fd779a)

**Comment by Sidiusz** [comment]
С точкой тоже хорошо!

**Comment by simply-kel** [comment]
Внесены изменения в [commit](https://github.com/simply-kel/SimplyStatus-fabric/commit/8394f50a5d5d4caf94329b51f8da7037f7895872)
